# Generated by Django 6.0.6 on 2026-06-16 06:29

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('requests_app', '0002_alter_bloodrequest_blood_group'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AIIntakeLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_input', models.TextField()),
                ('ai_output', models.JSONField()),
                ('confidence_score', models.FloatField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('blood_request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_logs', to='requests_app.bloodrequest')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='ai_intake_logs', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ai_intake_logs',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['confidence_score'], name='ai_intake_l_confide_9b3c64_idx'), models.Index(fields=['created_at'], name='ai_intake_l_created_5e7699_idx')],
            },
        ),
    ]
