# Generated by Django 6.0.6 on 2026-06-15 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='blood_group',
            field=models.CharField(blank=True, max_length=3, null=True),
        ),
    ]
