# Generated by Django 6.0.6 on 2026-06-15 09:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0002_alter_bloodrequest_blood_group'),
    ]

    operations = [
        migrations.AddField(
            model_name='bloodrequest',
            name='additional_notes',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='time_window_hours',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='units_needed',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='bloodrequest',
            name='urgency',
            field=models.CharField(max_length=20),
        ),
    ]
