# Generated by Django 6.0.6 on 2026-07-02 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0003_bloodrequest_latitude_bloodrequest_longitude_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bloodrequest',
            name='status',
            field=models.CharField(choices=[('Waiting', 'Waiting'), ('Notification Sent', 'Notification Sent'), ('Accepted', 'Accepted'), ('Rejected', 'Rejected'), ('Completed', 'Completed')], default='Waiting', max_length=20),
        ),
    ]
