# Generated by Django 6.0.6 on 2026-07-04 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('requests_app', '0004_alter_bloodrequest_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bloodrequest',
            options={'ordering': ['-id']},
        ),
        migrations.AlterModelOptions(
            name='emergencynotification',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='bloodrequest',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
