# Generated by Django 6.0.6 on 2026-06-29 09:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='donor',
            name='accepted_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='average_response_time',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='last_donation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='donor',
            name='latitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='donor',
            name='longitude',
            field=models.FloatField(default=0.0),
        ),
        migrations.AddField(
            model_name='donor',
            name='rejected_count',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='donor',
            name='reliability_score',
            field=models.FloatField(default=100.0),
        ),
        migrations.AddField(
            model_name='donor',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donor_profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
