# Generated by Django 6.0.6 on 2026-07-04 18:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('donors', '0002_donor_accepted_count_donor_average_response_time_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='donor',
            options={'ordering': ['-id']},
        ),
    ]
