# Generated by programmatic migration helper

from django.db import migrations
from django.contrib.auth.hashers import make_password

def create_default_coordinator(apps, schema_editor):
    # Retrieve the auth User model
    User = apps.get_model('auth', 'User')
    
    username = 'fathimarinsha'
    email = 'fathimarinsha@lifelink.ai'
    password = 'password123'
    
    if not User.objects.filter(username=username).exists():
        User.objects.create(
            username=username,
            email=email,
            password=make_password(password),
            is_staff=True,
            is_superuser=True
        )

def remove_default_coordinator(apps, schema_editor):
    User = apps.get_model('auth', 'User')
    User.objects.filter(username='fathimarinsha').delete()

class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_default_coordinator, reverse_code=remove_default_coordinator),
    ]
